apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
    name: cs-api-servicos-online
    namespace: cs-homolog
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      app: cs-api-servicos-online
      deploymentconfig: cs-api-servicos-online
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: cs-api-servicos-online
          deploymentconfig: cs-api-servicos-online
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/cs-homolog/cs-api-servicos-online@sha256:a9030c8878d61c2e63ef62330c06666c9e4bcb99d6d4e90530111a4ee2f4dab7
          imagePullPolicy: IfNotPresent
          name: cs-api-servicos-online
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 250m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cs-api-servicos-online
        from:
          kind: ImageStreamTag
          name: cs-api-servicos-online:4231
          namespace: cs-homolog
        lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/cs-homolog/cs-api-servicos-online@sha256:a9030c8878d61c2e63ef62330c06666c9e4bcb99d6d4e90530111a4ee2f4dab7
      type: ImageChange
    - type: ConfigChange
