apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      app.openshift.io/route-disabled: "false"
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2023-08-14T20:03:57Z"
    generation: 13
    labels:
      app: cs-api-servicos-online
      app.kubernetes.io/component: cs-api-servicos-online
      app.kubernetes.io/instance: cs-api-servicos-online
      app.kubernetes.io/name: cs-api-servicos-online
      app.kubernetes.io/part-of: cs-api-servicos-online-app
      app.openshift.io/runtime: spring-boot
      app.openshift.io/runtime-namespace: cs-homolog
      app.openshift.io/runtime-version: "4231"
    name: cs-api-servicos-online
    namespace: cs-homolog
    resourceVersion: "22182214"
    uid: 7d39954b-29e3-4b59-b537-12d57ea27e0d
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      app: cs-api-servicos-online
      deploymentconfig: cs-api-servicos-online
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: cs-api-servicos-online
          deploymentconfig: cs-api-servicos-online
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/cs-homolog/cs-api-servicos-online@sha256:a9030c8878d61c2e63ef62330c06666c9e4bcb99d6d4e90530111a4ee2f4dab7
          imagePullPolicy: IfNotPresent
          name: cs-api-servicos-online
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 250m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cs-api-servicos-online
        from:
          kind: ImageStreamTag
          name: cs-api-servicos-online:4231
          namespace: cs-homolog
        lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/cs-homolog/cs-api-servicos-online@sha256:a9030c8878d61c2e63ef62330c06666c9e4bcb99d6d4e90530111a4ee2f4dab7
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2023-08-14T20:57:41Z"
      lastUpdateTime: "2023-08-14T20:57:45Z"
      message: replication controller "cs-api-servicos-online-12" successfully rolled
        out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-08-14T21:34:15Z"
      lastUpdateTime: "2023-08-14T21:34:15Z"
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    details:
      causes:
      - type: Manual
      message: manual change
    latestVersion: 12
    observedGeneration: 13
    readyReplicas: 3
    replicas: 3
    unavailableReplicas: 0
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
