apiVersion: v1
kind: Secret
metadata:
  namespace: poc-sonda-utilities
  name: cs-api-servicos-online-hml
type: Opaque
# oracle settings
stringData:
  DATASOURCE_USERNAME: proxyuser
  SRV_ONLINE_USER: SRV_ONLINE
data:
  DATASOURCE_PASSWORD: cHJveHlwYXNzd2Q=
  PROXY_ROLE: VUVfQUxU
  PROXY_ROLE_PASSWORD: RE1DRDg4NDQwRE0yRjg4NDI0
  SRV_ONLINE_PASSWORD: JDBuZGFAMjI=
