apiVersion: v1
kind: Service
metadata:
  name: cs-api-servicos-online
  namespace: sonda
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: cs-api-servicos-online
  type: LoadBalancer
