apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cs-api-servicos-online
  namespace: poc-sonda-utilities
spec:
  params:
    - name: SOURCE_IMAGE
      type: string
    - name: SOURCE_TLS_VERIFY
      type: string
      default: 'false'
    - name: DESTINATION_IMAGE
      type: string
    - name: DESTINATION_TLS_VERIFY
      type: string
      default: 'false'
  tasks:
    - name: copy-image
      taskRef:
        kind: Task
        name: copy-image
      params:
        - name: SOURCE_IMAGE
          value: $(params.SOURCE_IMAGE)
        - name: SOURCE_TLS_VERIFY
          value: $(params.SOURCE_TLS_VERIFY)
        - name: DESTINATION_IMAGE
          value: $(params.DESTINATION_IMAGE)
        - name: DESTINATION_TLS_VERIFY
          value: $(params.DESTINATION_TLS_VERIFY)
