apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment
  namespace: sonda
spec:
  params:
    - name: GIT_REPOSITORY
      type: string
    - name: GIT_USER_NAME
      type: string
    - name: GIT_USER_EMAIL
      type: string
    - name: DEPLOYMENT_FILE
      type: string
      default: 'deployment.yaml'
  steps:
    - image: docker.io/alpine/git:2.36.3
      env:
        - name: GIT_REPOSITORY
          value: $(params.GIT_REPOSITORY)
        - name: GIT_USER_NAME
          value: $(params.GIT_USER_NAME)
        - name: GIT_USER_EMAIL
          value: $(params.GIT_USER_EMAIL)
        - name: DEPLOYMENT_FILE
          value: $(params.DEPLOYMENT_FILE)
      script: |

        git config --global user.name "${params.GIT_USER_NAME}"
        git config --global user.email "${params.GIT_USER_EMAIL}"

        git clone ${params.GIT_REPOSITORY} && cd "$(basename "$1" .git)"

        sed -i "/^\([[:space:]]*image: \).*/s//\1$1/" ${DEPLOYMENT_FILE}
