apiVersion : apps/v1
kind: Deployment
metadata:
  name: cs-api-servicos-online
  #namespace: sonda
  annotations:
    configmap.reloader.stakater.com/reload: cs-api-servicos-online-hml
    secret.reloader.stakater.com/reload: cs-api-servicos-online-hml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cs-api-servicos-online
  template:
    metadata:
      labels:
        app: cs-api-servicos-online
    spec:
      containers:
        - name: cs-api-servicos-online
          image: image-registry.openshift-image-registry.svc.cluster.local:5000/sonda/cs-api-servicos-online:4231
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
          ports:
            - containerPort: 8080
          # Config from ConfigMap
          envFrom:
            - secretRef:
                name: cs-api-servicos-online-hml
            - configMapRef:
                name: cs-api-servicos-online-hml
