apiVersion: v1
kind: ConfigMap
metadata:
  #namespace: cs-qa
  name: cs-api-servicos-online-qa
data:
  # spring boot context
  PORTA: '8080'

  # oracle settings
  DATASOURCE_URL: 'jdbc:oracle:thin:@172.28.187.2:1524:recomsp2'

  # hibernate config
  SPRING_JPA_DATABASE_PLATFORM: 'com.sonda.servicos.online.config.CustomOracleDialect'
  SPRING_SHOW_SQL: 'true'
  SPRING_OPEN_IN_VIEW: 'false'
  SPRING_HIBERNATE_PARAM_NULL_PASSING: 'true'

  # swagger
  SWAGGER_AMBIENTE: QUALIDADE
  LOGGING_LEVEL: 'INFO'
