apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-customisations
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: app/
    repoURL: 'https://gitlab.com/abass0/poc-sonda-utilities'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true