apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs-api-homolog
  namespace: openshift-gitops
spec:
  destination:
    namespace: cs-api-homolog
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: environments/homolog
    repoURL: https://github.com/abass0/poc-sonda-utilities
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true