apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-api-pipeline
  namespace: openshift-gitops
spec:
  destination:
    namespace: sonda
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: pipeline
    repoURL: https://github.com/abass0/poc-sonda-utilities
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true